version: '3.5'

services:
  db:
    image: mariadb:10.5
    container_name: librenms_db
    network_mode: "host"
    environment:
      - MYSQL_DATABASE=librenms
      - MYSQL_USER=librenms
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    command:
      - "mysqld"
      - "--sql-mode="
      - "--innodb-file-per-table=1"
      - "--lower-case-table-names=0"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped

  librenms:
    image: librenms/librenms:latest
    container_name: librenms
    hostname: librenms
    network_mode: "host"
    environment:
      - DB_HOST=127.0.0.1
      - DB_NAME=librenms
      - DB_USER=librenms
      - DB_PASSWORD=password
      - TZ=America/Bogota
      - BASE_URL=http://192.168.1.164:8000
    volumes:
      - librenms-data:/data
    depends_on:
      - db
    restart: unless-stopped

volumes:
  librenms-data:
  db-data:
